### ISSUE TITLE
Analyze simply hangs

### ISSUE THREAD

**Issue by robtarr** [codeclimate/codeclimate#238] opened 2015-12-01 18:18 UTC
When I run 
```docker run \
  --interactive --tty --rm \
  --env CODE_PATH="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate```

I get the `help` list with what commands are available

Running
```docker run \
  --interactive --tty --rm \
  --env CODE_PATH="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate analyze```

simply hangs with no output whatsoever. :confused: 

```docker run \
  --interactive --tty --rm \
  --env CODE_PATH="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate validate-config```

outputs: `No errors or warnings found in .codeclimate.yml file.`

My `.codeclimate.yml` file:
```
exclude_paths:
- "src/vendor/*"
- "app.js"
engines:
  eslint:
    enabled: true
```

Any help would be GREATLY appreciated - thanks.

**Comment by robtarr** [comment] 2015-12-01 18:41
It is a private repo, and has about 180 files. I let it run for at least 30 minutes with no output. Considerably longer than it takes on the hosted instance of CodeClimate.

**Comment by robtarr** [comment] 2015-12-01 19:12
I just ran ```docker run \ --interactive --tty --rm \ --env CODE_PATH="$PWD" \ --volume "$PWD":/code \ --volume /var/run/docker.sock:/var/run/docker.sock \ --volume /tmp/cc:/tmp/cc \ codeclimate/codeclimate analyze``` on a MUCH smaller project (30 files), and I get the exact same result.

**Comment by robtarr** [comment] 2015-12-02 01:59
If I cancel it, it seems to always dump this to the console: 
```/usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``': Interrupt
	from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:70:in `gitignore_paths'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:65:in `exclude_paths'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:36:in `engine_config'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:25:in `block in run'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:23:in `each'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:23:in `map'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:23:in `run'
	from /usr/src/app/lib/cc/analyzer/engines_runner.rb:51:in `configs'
	from /usr/src/app/lib/cc/analyzer/engines_runner.rb:55:in `engines'
	from /usr/src/app/lib/cc/analyzer/engines_runner.rb:19:in `run'
	from /usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
	from /usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
	from /usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
	from /usr/src/app/lib/cc/cli/command.rb:24:in `execute'
	from /usr/src/app/lib/cc/cli/runner.rb:27:in `run'
	from /usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	from /usr/src/app/bin/codeclimate:9:in `<main>'```

**Comment by devinus** [comment] 2015-12-02 02:20
Experiencing the same issue on a pretty standard Ember project. I get NO feedback whatsoever and my laptop sounds like it's about to take off.

**Comment by robtarr** [comment] 2015-12-02 03:34
I just let analyze run for about 20 minutes on my small project, and it came back with results!

Why does it take so long???? Most of that time was with no output, and then it seemed to run the analysis quickly and then stop.

**Comment by robtarr** [comment] 2015-12-02 03:45
Is this not the right way to exclude folders?
```engines:
  eslint:
    enabled: true
exclude_paths:
- node_modules```

I removed the `node_modules` folder, and it worked fine.

**Comment by wfleming** [comment] 2015-12-02 16:21
Sorry for the delayed response, guys. This does seem related to a known issue with how we process exclude paths, though the degree to which the performance is unacceptable is far more extreme for you than we'd previously seen.

We're looking into a fix soon, but in the meantime you might want to comment out those `exclude_paths`, as a workaround. The trade-off is that the CLI will then report issues for those files of course, which may be annoying until we get this fixed.

**Comment by robtarr** [comment] 2015-12-02 21:26
I tried that. The problem is, that unless I remove the `node_modules` folder, it examines the whole folder, and that takes a LONG time, as there are a lot fo modules being included.

**Comment by nervetattoo** [comment] 2015-12-08 12:54
I can confirm this behaviour.
I tried running from the console as well, with the same (no) results.
This is on a big project so I don't even have the patience to let it run without the exclude paths and get a result back.

**Comment by frobichaud** [comment] 2015-12-15 05:07
Same issue here, attempting to run a simple bundler-audit takes over a minute, while it takes 2 seconds on online codeclimate.com.

Execution time:
<img width="394" alt="screen shot 2015-12-15 at 12 04 19 am" src="https://cloud.githubusercontent.com/assets/3533748/11802507/86bd2714-a2bf-11e5-877e-3ed4c25d71a7.png">

Online bundler-audit:
<img width="922" alt="screen shot 2015-12-15 at 12 04 03 am" src="https://cloud.githubusercontent.com/assets/3533748/11802505/8227644e-a2bf-11e5-99aa-2159557ec28d.png">

Processes:
<img width="584" alt="screen shot 2015-12-15 at 12 03 43 am" src="https://cloud.githubusercontent.com/assets/3533748/11802503/7c392b8a-a2bf-11e5-9ae0-82fde90fae2a.png">


I'm just getting started with docker, but what I see here is lots of CPU overhead being consumed by the VBoxHeadless process.

**Comment by frobichaud** [comment] 2015-12-15 23:41
Is there any major difference between the codeclimate-cli and the cloud service? I've tried virtualbox, vmware fusion and attempted some changes with file sharing. I still can't pinpoint the root cause of my issue.

**Comment by pbrisbin** [comment] 2015-12-16 16:28
> Is there any major difference between the codeclimate-cli and the cloud service?

The performance bottleneck we're suspicious of here is the building of the paths we send to the engine for analysis. They're built by looking at the source directory's contents in conjunction with your configured `exclude_paths`. It can be slow on a project with many files and/or complicated excludes.

One reason it could be fast on codeclimate.com but slow locally is if you have many files not checked into git (e.g. `node_modules`). codeclimate.com would not see these files at all since it does a fresh clone and only has tracked files in the local source directory. CLI on the other hand has all files present, tracked or untracked, when building these paths.

Conceptually, adding such untracked and problematic files to `exclude_paths` should be the same as if they didn't exist and therefore make the CLI perform like on codeclimate.com, but it's not that easy: since the performance issue lies exactly with the process of working with exclusions, having files present but excluded has very different performance characteristics than not present at all.

**Comment by winkler1** [comment] 2015-12-31 15:55
Having the same experience... this is really bad. No feedback at all, crazy slow even after turning off all engines. I've setup feedback loops with Karma, Guard, eslint, rubocop. Things run in seconds. The whole point of doing this is fast feedback on the dev's machine.

Instead of fighting with the exclude_paths stuff, I'd suggest being able to specify `include_paths`. If given, just look in those whitelisted dirs. That way people could hone in one one folder and get things working quickly.

IMO, this should be done be default in `codeclimate initialize` for something like a Rails app. You know where the code's going to be by convention.

Something that takes more than a minute without feedback is impenetrable and will not be used.

**Comment by sb8244** [comment] 2016-01-04 01:13
I am also experiencing this issue.

**Comment by ccoffey** [comment] 2016-01-11 00:07
I am experiencing the same problem. I let ```codeclimate analyze``` run for 20 minutes with no output, then I did ```rm -rf node_modules``` and ran ```codeclimate analyze``` again and saw output after 1 minute.

**Comment by Domon** [comment] 2016-01-14 07:56
Same issue here. Is there any option like `--verbose` that we can turn on to see what causes `analyze` hangs?

**Comment by wfleming** [comment] 2016-01-22 20:51
Hi all,

Sorry for the delay on this. We have a PR open now (#308) that we believe will fix these problems. We're hoping to release that fix soon, but until we do we'd encourage anybody having this problem to take a look at that PR & try using a local build of that branch to see if it solves this for you.

If you'd like to try out that branch, these would be the steps:

```shell
$ git clone https://github.com/codeclimate/codeclimate.git
$ cd codeclimate
$ git checkout will-pb/serenity-now
$ make
```

The `make` task will build a docker image of the CLI, which will then get used whenever you run `codeclimate` locally.

If you're still finding that this version hangs for a very long time before it starts running any engines when you run `codeclimate analyze`, please let us know.

**Comment by prrrnd** [comment] 2016-01-23 16:31
@wfleming 
I'm also having the issue where `analyze` is just hanging. 
The project I'm trying it on is a small ruby on rails application. 
The steps in your previous comment didn't fix the problem.

**Comment by wfleming** [comment] 2016-01-23 19:32
@prrrnd Thanks for the report. I don't suppose that app is public by any chance?

If not, other details that could help us:

1. Can you share the stack-trace/any output you see if you you kill the command while it's hanging?
2. Are there are any large vendor-oriented directories under your local project directory (e.g. `.bundle`, `node_modules`, etc.)?
3. Do you have any symlinked directories under your repo directory that might lead to loops, that you know about?
4. Can you share the contents of your `.codeclimate.yml`?

Thanks.

**Comment by prrrnd** [comment] 2016-01-24 08:55
@wfleming 

1. After `ctrl + c`
```
/usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``': Interrupt
	from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:70:in `gitignore_paths'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:65:in `exclude_paths'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:60:in `include_paths'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:37:in `engine_config'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:25:in `block in run'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:23:in `each'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:23:in `map'
	from /usr/src/app/lib/cc/analyzer/engines_config_builder.rb:23:in `run'
	from /usr/src/app/lib/cc/analyzer/engines_runner.rb:51:in `configs'
	from /usr/src/app/lib/cc/analyzer/engines_runner.rb:55:in `engines'
	from /usr/src/app/lib/cc/analyzer/engines_runner.rb:19:in `run'
	from /usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
	from /usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
	from /usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
	from /usr/src/app/lib/cc/cli/command.rb:24:in `execute'
	from /usr/src/app/lib/cc/cli/runner.rb:27:in `run'
	from /usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	from /usr/src/app/bin/codeclimate:9:in `<main>'
```

2. No
3. No symlinked directories
4. Here is the `.codeclimate.yml`

```
---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
  - "**.js"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
```

`codeclimate validate-config` outputs `No errors or warnings found in .codeclimate.yml file.`

**Comment by wfleming** [comment] 2016-01-24 17:29
@prrrnd That stack trace indicates that you're still running the latest release build: several of the methods on the stack there don't exist in the branch that we think fixes this issue.

If you pull that branch again, I added a small change to the recorded version to make it a bit easier to confirm you're running the branch for the bugfix. Can you pull that branch & run `make` again please? Check the output of the `make` to see if it looks like anything went wrong. (If it's failing to install dependencies via `apt` or `bundle`, you may need to `stop` and `start` your `docker-machine`: there's a bug we've seen with `docker-machine` where sometimes the VM seems to lose net connectivity to its host machine.)

When the branch is built successfully, running `codeclimate --version` should echo `0.18.0-alpha.workspace`.

**Comment by prrrnd** [comment] 2016-01-24 19:38
@wfleming Seems to be working now! Thanks :+1:

**Comment by eduardojmatos** [comment] 2016-01-28 21:14
@wfleming here worked well, thank you! :smile:

**Comment by wfleming** [comment] 2016-02-01 16:51
[v0.18.0](https://github.com/codeclimate/codeclimate/releases/tag/v0.18.0) has been shipped, so our fix for this is now fully released. I'm going to close this issue, but if anybody here continues to experience this on the new release, please feel free to re-open with details.

**Closed by wfleming** 2016-02-01 16:51 UTC

**Comment by khpeek** [comment] 2018-02-20 19:26
I'm running version `0.71.1` of CodeClimate, but I'm still running into an issue of a `codeclimate analyze` command hanging. It has been running for >10 minutes:

```
Kurts-MacBook-Pro:lucy kurtpeek$ codeclimate analyze
Starting analysis
Running structure: -
```
Using the website, I estimate it takes about a minute. According to my `git status` there are no large untracked files. Why the discrepancy?

**Comment by maxjacobson** [comment] 2018-02-20 19:36
Hi Kurt. The usual explanation for this is that, on codeclimate.com, we do a fresh clone of the repository before analysis. On your computer, it's possible that there are extra files there which are ignored by git because of your `.gitignore`. To confirm if that is impacting analysis time, would you please do a fresh clone of your repository and run `codeclimate analyze` on that?

**Comment by khpeek** [comment] 2018-02-20 19:46
Hi Max,

Thanks for your quick reply. I ran `codeclimate analyze` on a fresh clone
of my repository and it was indeed much faster.

Just from comparing the sizes of the 'worked-on' repository, `lucy`, and
the 'fresh' one, `lucy3`, I still don't see why it would take so much
longer because their sizes are not that different:

Kurts-MacBook-Pro:dev kurtpeek$ ls -lh

total 0

drwxr-xr-x  11 kurtpeek  staff   352B Feb 16 10:07 lucy

drwxr-xr-x   9 kurtpeek  staff   288B Jan 24 13:26 lucy2

drwxr-xr-x  10 kurtpeek  staff   320B Feb 20 11:40 lucy3

Is there a way to get it to work fast on the original `lucy` repository?

Best,
Kurt

**Comment by maxjacobson** [comment] 2018-02-20 20:10
Hm I'm skeptical that the directory _and all its contents_ is actually 288 bytes. I think that's probably just the size of the directory, but not its contents.  You can run `du -sh lucy` and `du -sh lucy3` to confirm the full size

**Comment by maxjacobson** [comment] 2018-02-20 20:11
Further, you can use a tool like ncdu (`brew install ncdu` and then `ncdu lucy` to determine which files are making up that size

**Comment by khpeek** [comment] 2018-02-20 21:10
Hi Max,

Thanks for your reply, you're totally right: the `lucy3` directory is 177M
whereas `lucy` is 1.3G. A large part of the difference are the
`node_modules` in one of the subdirectories.

That said, I don't suppose it is possible to run `codeclimate analyze` in
such a way that it ignores files in `.gitignore`s, so that its performance
would be similar to running it on a fresh clone?

Best,
Kurt

**Comment by maxjacobson** [comment] 2018-02-20 21:30
The best thing to do in the short term is to add node_modules to your `exclude_patterns` (more context here: https://docs.codeclimate.com/docs/excluding-files-and-folders). We have considered respecting the gitignore in the past (and I think we might have _tried_ to do that at one point) but I think it was too complex to support correctly. I'll make a note of it as a feature request internally and we'll definitely talk about it internally soon. Thanks for the nudge.
