### ISSUE TITLE
ERROR: brew install codeclimate

### ISSUE THREAD

**Issue by jspizziri** [codeclimate/codeclimate#17] opened 2015-06-22 14:48 UTC
```sh
$ brew install codeclimate
==> Installing codeclimate from codeclimate/homebrew-formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.0.7.tar.gz
==> Downloading from https://codeload.github.com/codeclimate/codeclimate/tar.gz/v0.0.7
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: ce5efec690264565e1342b50329a03e8aa39e276
Actual: 9e2b70d12d89ba85cc0174fed5aa473b500a5f12
Archive: /Library/Caches/Homebrew/codeclimate-0.0.7.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by GordonDiggs** [comment] 2015-06-22 15:00
Duplicate of #16.

This should be fixed. Try `brew update` and then install again

**Closed by GordonDiggs** 2015-06-22 15:00 UTC
