### ISSUE TITLE
Stuck in `running duplication` for hours

### ISSUE THREAD

**Issue by nadeemja** [codeclimate/codeclimate#431] opened 2016-05-07 09:34 UTC
Hi guys,

Just installed codeclimate on my OS X El Capitan, and it looks promising.

However, `codeclimate analyze` gets stuck on `Running duplication`. `Running csslint` gets done rather quickly, though.

Please let me know how I can help you help me. What info do you need? 

Thanks and regards,

Nadeem.

**Comment by nadeemja** [comment] 2016-05-07 12:52
PS. Seems like it might not really be stuck, just taking a long time, based on the fact that it completed on a folder with only one file with a single. Any way to run it more verbosely?

**Comment by pbrisbin** [comment] 2016-05-07 13:11
Hi @nadeemja sorry for the trouble here. There's a few things worth looking into:

- The engine is running for a long time

  This can happen to any engine for a variety of reasons. Most often, the engine is analyzing files or directories it shouldn't. Configuring exclusions (overall or per engine) would be the answer here. Sometimes there is a bug or performance regression in the engine itself. If that turns out to be the case, we can open it as an issue on codeclimate/codeclimate-duplication and go from there.

- The engine isn't timing out after 15 minutes

  This is a bit more concerning. Engines run under a strict timeout and a `docker kill` should be invoked after it's expired. If that's not happening in this case, I'd definitely like to understand why.

As for verbosity, you may find useful information by running with DEBUG enabled:

```
CODECLIMATE_DEBUG=1 codeclimate analyze -e duplication
```

The best way for us to help investigate would be if we had a copy of the project to experiment in. If it's not OSS, would you be willing to email me an archive (pat at codeclimate.com)?

**Comment by nadeemja** [comment] 2016-05-07 14:00
Hi pbrisbin,

Thank you for a such a thoughtful answer. 
Such things are rare, and I'm really, really grateful to you.

I've run `codeclimate analyze` a few more this, and this last time it actually timed out with:
  
  error: (CC::Analyzer::Engine::EngineTimeout) engine duplication ran for 900 seconds and was killed

I think my Macbook might've suspended the process after inactivity from my part (screen goes black even though i'm AC).

I'll try configuring exclusions and come back to you :)

**Comment by nadeemja** [comment] 2016-05-07 17:04
Update:

I'm running MeteorJS and added the following exclusion paths:

    - ".meteor/"
    - ".git/"
    - "public/"

The duplication stage now passes. Yay! - and again many thanks.

The eslint stage just passed also. __19'360 issues__. 

Any chance codeclimate does autofix?

**Comment by pbrisbin** [comment] 2016-05-09 00:23
Oof. Unfortunately the CLI doesn't have autofix (yet), and in this case neither does the underlying tool (eslint).

FWIW, such a high number of issues is often due to a small number of checks that you don't particularly care about or have your own opinions for (indentation level, for example), so a small `.eslintrc` adjustment may have a large impact on getting that number down to something manageable.

I'm going to go ahead and close this issue, since it looks like your "stuck" duplication engine has been addressed. If that's not the case, feel free to re-open.

**Closed by pbrisbin** 2016-05-09 00:23 UTC
