### ISSUE TITLE
Can't get exclude_paths to work

### ISSUE THREAD

**Issue by iainbryson** [codeclimate/codeclimate#644] opened 2017-04-25 23:56 UTC
Everything seems to work on the command line codeclimate on my OSX box, except for excluded paths.  Here's my .codeclimate.yml:

```
---
engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          exclude_paths:
          - "./assets/javascripts/mathjax.js"
          - "./assets/javascripts/edit-page.js"
          - "**.js"
  eslint:
    enabled: true
    exclude_paths:
    - "assets/javascripts/mathjax.js"
    - "assets/javascripts/edit-page.js"
    - "**.js"
    - "assets/javascripts/"
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "assets/javascripts/mathjax.js"
- "assets/javascripts/edit-page.js"
- "**.js"
```

I've tried (as you can see) various combinations of path and pattern matches (prefix with `./`, etc...)  but nothing seems to work.  The two problematic files are external ones I don't have time to refactor ATM, so I'm looking to simply disable them.

I'm working in the app folder of a rails app because without exclusions running codeclimate from the root take too long (using bower and vendor paths, etc..)

Despite futzing with the config a lot, I continue to get the following errors:

```
== assets/javascripts/edit-page.js (13 issues) ==
34: Move the invocation into the parens that contain the function. [eslint]
46-60: Identical code found in 1 other location (mass = 76) [duplication]
77-80: Identical code found in 1 other location (mass = 55) [duplication]
116-120: Similar code found in 1 other location (mass = 74) [duplication]
116: Expected a conditional expression and instead saw an assignment. [eslint]
134: Function 'removeMath' has too many statements (34). Maximum allowed is 30. [eslint]
134: Function 'removeMath' has a complexity of 15. [eslint]
146-162: Similar code found in 1 other location (mass = 93) [duplication]
188-199: Similar code found in 2 other locations (mass = 47) [duplication]
226-232: Identical code found in 1 other location (mass = 47) [duplication]
282: Move the invocation into the parens that contain the function. [eslint]
290-301: Similar code found in 1 other location (mass = 104) [duplication]
303-314: Similar code found in 1 other location (mass = 104) [duplication]

== assets/javascripts/mathjax.js (11 issues) ==
45-48: Identical code found in 1 other location (mass = 55) [duplication]
61-78: Similar code found in 1 other location (mass = 93) [duplication]
91-125: Similar code found in 2 other locations (mass = 47) [duplication]
111-124: Similar code found in 2 other locations (mass = 47) [duplication]
149-155: Identical code found in 1 other location (mass = 47) [duplication]
193-206: Identical code found in 1 other location (mass = 76) [duplication]
239-243: Similar code found in 1 other location (mass = 74) [duplication]
264-275: Similar code found in 1 other location (mass = 102) [duplication]
276-286: Similar code found in 1 other location (mass = 102) [duplication]
287-295: Similar code found in 1 other location (mass = 70) [duplication]
296-304: Similar code found in 1 other location (mass = 70) [duplication]

```

I've run the update, and the output of the following command:

```
$ docker run   --interactive --tty --rm   --env CODECLIMATE_CODE="$PWD"  --env CODECLIMATE_DEBUG=1  --volume "$PWD":/code   --volume /var/run/docker.sock:/var/run/docker.sock   --volume /tmp/cc:/tmp/cc   codeclimate/codeclimate analyze /code > out
```

is here:

https://gist.github.com/iainbryson/8c022a144a0b6bd9829638c80cea814a

Here's my install:

  ```
 $  uname -a
Darwin Iains-MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
 $   docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64

 $   env | grep "^DOCKER_"
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
  ```

**Comment by wfleming** [comment] 2017-04-27 02:52
Hi @iainbryson,

Thank you for providing so much detail & the debug output. I think the root cause here is indicated by the line at the top of the debug output:

```
[DEBUG] Couldn't include because part of path doesn't exist. path="./code"
```

Specifying `/code` as a path to analyze when you run `codeclimate analyze` is causing unexpected behavior. The `/code` path is an implementation detail of how the CLI makes code available to engines for analysis internally, but you don't need to specify it when running the command: you can just run `codeclimate analyze` (either with our [wrapper script](https://github.com/codeclimate/codeclimate/blob/master/codeclimate-wrapper) or as the full docker invocation like you shared here).

When you do specify a path argument to `analyze`, the path should be relative to your project root, and `exclude_paths` are not applied when an explicit path is specified. So when you pass `/code`, the CLI can't find that subdirectory and falls back to analyzing the entire repository, and doesn't apply exclude paths because an explicit path was provided. (This failure case should probably error more explicitly than just logging a debug message, sorry.) There's more detail on this behavior in the `analyze` entry under the ["Commands" section of the README](https://github.com/codeclimate/codeclimate/blob/master/README.md#commands)

So if you just run `codeclimate analyze` without a path, I hope you'll see your exclude paths there being respected.

One other small note about the config you shared: I realize you were probably just starting to add `exclude_paths` everywhere to make it work, but an `exclude_paths` entry under the language name for `duplication` isn't a valid configuration. If you did want to exclude only specific files for the `duplication` engine that key would need to be at the same indentation level as `enabled` and `config` under `duplication`, e.g. the same as the `exclude_paths` entry you have for `eslint`. Similarly, if you want to exclude `assets/javascripts/mathjax.js` entirely you only need it in the top-level `exclude_paths` entry, not the engine-specific ones. Again, I realize you were probably just adding it everywhere while debugging, just mentioning it.

If you're still not seeing these files excluded when running `codeclimate analyze` without any path specified, please let us know here. Output of `CODECLIMATE_DEBUG=1 codeclimate analyze` in that case would also be very helpful.

**Comment by iainbryson** [comment] 2017-05-15 18:46
Great, thanks Will!  I’m not sure why I added `/code`; I think I was trying to debug something and then it just stayed along.

**Comment by jhabdas** [comment] 2017-05-16 04:13
Potential root cause #660

**Comment by ABaldwinHunter** [comment] 2017-05-31 15:43
Thanks for the feedback. Going to go ahead and close this as it appears resolved, along with https://github.com/codeclimate/codeclimate/issues/660.

Please feel free to reopen if you're still encountering the same issue.

**Closed by ABaldwinHunter** 2017-05-31 15:43 UTC
