### ISSUE TITLE
Engine timeout :(

### ISSUE THREAD

**Issue by eproulx-petalmd** [codeclimate/codeclimate#270] opened 2015-12-12 21:47 UTC
Hi,

Brakeman engine's always run out of time when analyzing, but when running by itself, it takes about 2 minutes to get the entire results

Running codeclimate analyze:
```
Starting analysis
Running brakeman: Done!
error: (CC::Analyzer::Engine::EngineTimeout) engine brakeman ran for 900000 seconds and was killed
```
Here's my .codeclimate.yml
```
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
exclude_paths:
- app/chewy/*
- coverage/**/*
- log/**/*
- public/**/*
- bin/**/*
- api_doc/**/*
- doc/**/*
- tmp/**/*
- spec/**/*
- vendor/**/*

```

**Comment by pbrisbin** [comment] 2015-12-14 18:46
Hi, sorry about the trouble here.

Does your project happen to be open source? It'd be great if we could play with a copy ourselves to try and figure out what's going on.

**Comment by frobichaud** [comment] 2015-12-14 21:32
@pbrisbin, I raised the issue with codeclimate's support, they should be able to access our repo. I'm on the same team as @eproulx-petalmd and yes our repo is unfortunately private.
error: (CC::Analyzer::Engine::EngineTimeout) engine brakeman ran for 900000 seconds and was killed

**Comment by pbrisbin** [comment] 2015-12-14 21:54
Thanks @frobichaud, going via support is definitely the way to go. Do you mind if I close this issue so we're not tracking it in two places?

**Comment by frobichaud** [comment] 2015-12-14 22:15
@pbrisbin It could be nice to keep it open to expose our problem to the community. But it's up to you if you feel this is a duplicate.

**Comment by Kaijiro** [comment] 2015-12-21 15:53
I'm having the same issue when executing codeclimate with phpmd at root of a Wordpress Installation.
error: (CC::Analyzer::Engine::EngineTimeout) engine phpmd ran for 900000 seconds and was killed

I would like to know how to fix the problem.

**Comment by grahamlyons** [comment] 2016-02-01 15:50
I'm getting the same issue in a Ruby project. It runs fine using Code Climate as a Service.

**Comment by guy-mograbi-at-gigaspaces** [comment] 2016-02-17 10:31
me too.

**Comment by ricardo-pcan** [comment] 2016-03-14 17:36
me too

**Comment by pbrisbin** [comment] 2016-03-24 19:26
Hello folks, sorry for the delay here.

It seems this has become a classic "me-too" catch-all for general engine timeouts. These can occur for a variety of reasons and in any engine. At this point, we're relatively confident there's not a bug to be fixed in the CLI itself and so are going to close this issue.

There may be bugs (now or in the future) in specific engines making them more prone to timeouts. If that's the case, an issue opened on the specific engine would be preferable. We're always on the lookout for such cases (for example, I recently fixed such an issue in phpmd).

We have a trouble-shooting guide around engine timeouts available on our [docs site](https://docs.codeclimate.com/docs/troubleshooting-engine-timeouts) which may be useful.

@grahamlyons since you've mentioned that your analysis completes on codeclimate.com but errors locally, that's likely because the engine is spending (potentially a lot of) time operating on files not checked into git (`node_modules` is a common source of this trouble). I'd suggest trying to identify these files and excluding them from analysis via `.codeclimate.yml`.

**Closed** 2016-03-24 19:27 UTC

**Comment by boboldehampsink** [comment] 2016-04-16 09:15
I'm experiencing the same issue. Excluding .git, node_modules, vendor etc. doesn't resolve the issue.
